### ISSUE TITLE
Killing enemies / player and combat end

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#35]
## Feature Description

Make it so that reducing enemies to 0HP removes them from combat. Killing all enemies ends the combat.
Killing the player ends the combat.

## Motivation

Well... We need to make progress at one point and being stuck in the first combat because enemies want to chat while at 0HP doesn't seem like a good thing.

## Acceptance Criteria

[Define the criteria that need to be met for this feature to be considered complete.]

- Killing an enemy removes it from the list of enemies
- Killing all enemies ends the combat
- Killing the player ends the combat

## Proposed Solution

We need to check after every attack (and maybe even after every effect, but that part depends on how we want to do things, this is more a game design thing) if an enemy is at 0HP or less. Same for the player.
If he is, remove him from the combat and the list of enemies. If the list of enemies is empty, combat ends. We don't have anything to do after for now, but we can imagine having a **state machine to go between the different possibilities**. For now the state machine can just be a loop of combats, and we will add more states as the development goes on. This is at least good to test that the gameplay loop works correctly (no bug between combats like badly initialized enemies, keeping stats from previous combat, etc...)

## Additional Context

The enemies wanted to chat a bit longer... 
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/81eb99c7-c2ba-4dce-b715-524987aab02f)
Almost wanted to qualify this one as a bug but technically we just never talked about this part. I added some context as a TODO list at the end of `Battler.gd` so someone that takes this can refer to that for later.

**Comment by cheesefrycook** [comment]
Maybe we can check for the health depleting to zero in `Battler` since it has the list of enemies. From there we could send a signal to a global AutoLoad `SceneController` that handles whatever to do next. For now the `SceneController` could just reload `TestingScene` to confirm it works, but later on we could have the state machine as mentioned. Something like:
- Player death: show player death screen. Return to main menu when you click Next
- Enemies dead: show rewards screen. When rewards are collected, transition to map screen

Might also be good to add a new phase to `PhaseManager` called `GAME_OVER` that disables any combat interactions.

**Comment by Turtyo** [comment]
Yes i was thinking something like that. I need to push my changes to battler now that i'm back. So that we are working too much on battler at the same time with @Tomzkk

**Comment by Tomzkk** [comment]
I took a break from working on this waiting on that PR you mentioned before. @Turtyo 

I was trying to get this done at first by simply sending a signal from health component when hp reaches 0, but the issue is if we want to delete an enemy we would have to remove the reference from everywhere - including enemy list in battler. But enemy can die in the middle of their own turn (when the enemy dies to a poison for example) and at that point we shouldn't be deleting from the list as it's being iterated over. However we need to delete said enemy before enemies start performing actions (which is in the next loop) otherwise they would still attack or could be a target of other enemy's heals etc and be ressurecte. I think we'll need some way to "disable" an enemy from doing any actions or being a target of any action (this could ultimately also serve as a dead state and we wouldn't have to delete them altogether) -- that is, unless the core part of the battler will change in the PR you mentioned and removes/modifies this problem.

**Comment by Turtyo** [comment]
Poison is applied at turn start so they don't really die in the middle of their turn with this example.
If the problem is that some enemies can die during the effects of a card, we have two solutions:
- Either we apply all the effects of cards, then enemies with $\text{HP} \leq 0$ are removed from the list. So a card that deals 3 damages 3 times could attack an enemy that is already at negative value
- We remove enemies between effects. We can totally do that, since the list of enemies is not being iterated over at the point, only the list of effect is (and the effect can be given targets via the list of enemies, so we can update that between effects)

I might have missed your point, but currently I don't see a really big problem on updating the list of enemies. That said, i still need to properly introduce all the "targeting" I've been talking about since the card effect structure, which i will do once I've finished my PR for storing stats modifications.

**Comment by Tomzkk** [comment]
I was not really referring to during card play of the player, more so for the debuffs like poison and in case we wanted to delete enemies immediately. 

https://github.com/Saplings-Projects/1M_sub/blob/f0803c56ffc880e35d893819fc418b4a43e46978/Core/Battler.gd#L64-L80

_on_enemy_start_turn() are 2 loops through _enemy_list, first one applies debuffs and the second one is enemies attacking (or using any abilities they might have). What I meant was here, if an enemy dies during first loop (to poison), we can't delete him immediately as we are currently looping the _enemy_list (and would have to get rid of his reference from there)
However we can't wait for the end of the turn (and do all enemy deletions then) because after the statuses are resolved, enemies are going to attack/use their abilities which could result in dead enemy attacking us or other enemies healing the dead enemy back to life. 

That being said we can probably just make a function that will check all enemies and see if they have 0 hp then remove the dead ones and call it in more then 1 place rather then relying on instant deletion via a signal. That would also mean we would go with first option of applying all card effects at once before killing enemies - which is I believe how things mostly are in games I've played before ?

For clarification the stats modification PR is what I should wait for before this one right ?

**Comment by Turtyo** [comment]
Or we can just break enemy turn into 2 functions, one for turn start and one for enemy turn. I think I left that one function in the stat PR, though that will change some stuff.

**Comment by Turtyo** [comment]
So @Tomzkk , how do you plan on tackling this issue ? Since you self-assigned but the issue is not confirmed yet

**Comment by Tomzkk** [comment]
Oh right, I was mainly waiting to see how the stat PR would change things
In the current state, I think easiest and cleanest would be to handle deaths in battler and to check for any enemy deaths after any event that can result in it -- player playing a card, enemy start turn after statuses hit and then once more after an enemy action (this is assuming enemy can have an attack/action that would leave it dead)

The other thing is combat end - I'm not sure to what extent we want to resolve it in this PR. Simplest I can think of right now is just restarting the game once all enemies are dead or player dies. Similarly to the enemy dying, we can check if battle ended in battler after events that can lead to it - either player hp will be 0 or enemy list will be empty. Then having some sort of scene controller like it was already mentioned above, we could have that change the current scene and reload the test scene again. 
(Ideally we would want to go to next combat with existing player once enemies are defeated but currently deleting the scene also causes player to disappear along with it's stats - unless we make a more complex scene loader that would only replace the battler component inside of it with a fresh one somehow - but I'm not sure how that would work if at all - or resolve it in some other way)

**Comment by Turtyo** [comment]
Okay for enemy death. We can assume that some enemies may have an auto-destruct for example yes

What do you mean by restarting the game ? There might be different phases to the game, so combat end should be built around "go to next phase" more than than "restart the game". In our current state, next phase would be another combat since we don't have anything else.

I think a way to do that would be to have a more global node, a game manager for example, and it would call different things when starting phases. For example if we have a combat, it would start a battler, but an event it would start that.
The combat could send a signal when it ends that the battler would be listening to, and when it receives the signal it closes the battler and goes onto the next phase.
This game manager probably needs to be done separately, but for now we can imagine that the combat end is just emitting a signal that says that the combat ended. What do you think @Tomzkk ?

**Comment by Turtyo** [comment]
If you can implement the a basic control flow in this PR along with combat end then feel free to do so.
I agree that killing enemies after a card seems more natural (and also easier to implement), it would be up to the player to not overkill enemies (no need to use a apply 3 damages 4 times if the enemy has 1 HP for example)

**Comment by Turtyo** [comment]
@Tomzkk #43 is closed, so you can go ahead and start this PR

**Comment by Tomzkk** [comment]
Summary for proposed solution:

**1. Handling enemy deaths**

I believe based on discussion above we do not want to deal with enemy deaths inside of moves (such as during a card play that attacks multiple times etc). As such, we can check for deaths after actions that can result in them.

"killing enemies" in this case would mean after any such action, we go through list of enemies and check if any has died (0hp). If they did, we kill them by first removing them from all places where they are referenced (_enemy_list and party_component of other enemies) and ultimately we would erase them entirely. 

This needs to happen whenever a player plays a card - for this I would create a signal when card is played and listen to it in battler. Once player plays a card, do everything mentioned above.

It would also need to happen after enemy actions:

- enemies can die when their debuffs are settled at the start of their turn - for example to poison - so we check if this happened after they are all settled
-  enemies can also die as a result of their actions - for example enemies having suicide attacks or attacking players having thorns etc
    - here we again cannot check inside of the loop through enemy_list (as when we kill enemy we want to delete it from the list and doing that while iterating the same list is unsafe) -> we could do that after this loop but that can result in weird scenarios:

*for example -> enemy A suicide bombs, enemy B meant to heal him - if we handled deaths after the loop B would "ressurrect" A which is not supposed to happen*

As such I would rework the enemy attack loop to two separate loops as per @Turtyo's suggestion, where in the first one we go over the enemy_list and generate their actions - (enemy_action, enemy_that_casted, enemy_that_is_target) - and in second loop we go over this list and execute actions in order. Now after every action we can check if this action resulted in one of the enemies dying somehow - if A died and we get to action he wanted to perform, it is ignored. Another case is where A dies and someone else (B) wanted to do something to A (heal,buff,..) - in this case we will want to do something more - either B will change it's action after it finds out A has died or at least it would change the target to someone else [*or it does nothing and waits for a round*] -- (what exactly happens here is to be discussed and done in the future once we actually have more types of enemy actions - right now this will not happen since enemies only attack player with a simple attack so in this PR we will ignore these actions as well)

**2. End of combat**

- checking whether combat has ended should be simple - we can simply check whether the player has 0 hp OR all enemies are dead (enemy_list is empty) - we should be able to do this in the same places as those where we handle deaths of enemies (since they should cover all scenarios when combat can end as well)
-  here I am not fully sure what the consensus was for how much this PR should handle this - what should I try to do once I detect the combat has ended ?

**Comment by Turtyo** [comment]
I think you can put a placeholder for the case in which the enemy doesn't have a valid target anymore (a confused state for example, idk)

A question for the check you do when the player kills an enemy. We would need to go through the list of enemies and check which have 0 HP. We can directly remove while iterating there either. A solution for that could be:
- make an array `enemies_to_remove`
- when a player attacks, you do your check
- instead of directly removing, when you go through the list if an enemy has 0 HP you put them in the `enemies_to_remove` array
- now you do a while loop, with the condition `enemies_to_remove != []`, select the first of the list (or the last, that might be more effective, not that we have a lot of enemies to remove anyway) and you remove them from all relevant places
Since it's a while loop, there is no problem of removing while iterating over the list

The other parts seem good to me. To answer the question about what to do for combat end, you can just emit an `end_of_combat` signal and have a function reload a combat when it receives the signal (to check that it works properly).

**Comment by Tomzkk** [comment]
Yes, that was the plan - for now I'll just make it so that the action is skipped and maybe leave a comment behind so we know in the future

Yes, I'm aware, when I was playing with it before looking how things could be done I already did it through extra list - although I don't think we need a while loop there, since we are already looping through a different array (enemies to remove) and removing it from the original array it should be okay - for deleting I'll use queue_free and i am not accessing that enemy after the free anymore so I believe that is safe. 

Sure, sounds good

**Comment by Turtyo** [comment]
How do you plan on iterating on the `enemies_to_remove` array if you don't use a while loop ? A for-loop is out of the question, you will be deleting them from `enemies_to_remove` as well after having deleted them from everywhere else

**Comment by Tomzkk** [comment]
Why would we need to delete them from the enemies_to_remove list ? We just need to iterate over it, delete from the original enemy list and queue_free (which is to my knowledge and from what I've been looking up safe since we use queue and don't even access it after that call)

**Comment by Turtyo** [comment]
You remove them from the `enemies_to_remove` list to not remove them again later. If you kill enemy A, add it to the list, remove it from everywhere but the `enemy_to_remove` list, then kill enemy B, you add enemy B to `enemies_to_remove` but you left A in there (which is now empty), meaning you have a risk of trying to remove A again, which wouldn't make sense since you already did it.
Thus a while loop to remove the enemies of the `enemies_to_remove` list once they have been deleted from everywhere else
