### ISSUE TITLE
Github action is passing when local tests are not

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#51]
## Describe the bug
The Github action that helps us test using GUT is passing, but when pulling and running in local the tests are not running properly. This is not a problem with tests not passing, but tests not running properly and being hit with errors at runtime (for example calling a method on a null value).

## To Reproduce

- Pull the pull request #43 commit https://github.com/Saplings-Projects/1M_sub/pull/43/commits/b5499468d60e19ff9d48cf5008fa927b9957f516
- As we can see, the Github action is validated
- Run the tests in local
- You get "failed to load due to parse error", the test can't even run

Note that it also happens for https://github.com/Saplings-Projects/1M_sub/pull/43/commits/290dec72eb3cd0862e7f0fdf956eafe31baa92f7 but it's not a parse error this time, we get a runtime error ("Invalid get index 'battler_refrence' (on base: 'previously_freed')."

## Expected behavior
The Github action should fail if some tests can't be run

## Screenshots
I found this looking at the logs for https://github.com/Saplings-Projects/1M_sub/pull/43/commits/b5499468d60e19ff9d48cf5008fa927b9957f516 :
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/920ca415-2744-4b4e-bf7a-ea16b79226cd)

The reason is obviously wrong, as both files extend from GutTest, they just aren't parsed properly so the tests are not run at all.

For https://github.com/Saplings-Projects/1M_sub/pull/43/commits/290dec72eb3cd0862e7f0fdf956eafe31baa92f7 we get another log:
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/31627d79-7a80-454f-b74c-974d9e52fad5)
![image](https://github.com/Saplings-Projects/1M_sub/assets/49365680/bebbf415-0984-43ce-ba02-8d78ede90ce5)

This time, the tests exit when it should have hit an error. Actually the actual reason for the error is that I assign enemy to the root when it already exists inside the battler (so it can't assign).

## Possible fix

A first step should probably be to automatically fail in the following cases:
- any warning
- any orphan node

I am not sure this would cover all possibilities, as I believe we could other kind of runtime errors than orphans problems; further testing is probably needed to see if there are other runtime errors that are possible and that would not met the previous two criteria

**Comment by Turtyo** [comment]
If anyone could pull one of the two mentioned commit and check that the tests indeed don't run properly it would be nice
@Tysterman74 maybe ?

**Comment by Tysterman74** [comment]
Yo! Doing some digging and pulling https://github.com/Saplings-Projects/1M_sub/commit/b5499468d60e19ff9d48cf5008fa927b9957f516 it looks like running it locally fails due to an indentation error on `test_health.gd` but I think just from fixing the merge in your later commits should have fixed that indentation.

![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/87b0d897-0022-4c4a-9a00-b2b32a52cd85)

For https://github.com/Saplings-Projects/1M_sub/commit/290dec72eb3cd0862e7f0fdf956eafe31baa92f7 this one looks like we weren't freeing some resources up.

![image](https://github.com/Saplings-Projects/1M_sub/assets/5923102/f7dc3f89-a469-4ba7-9907-616152877f59)

BUT it looks to have been resolved in https://github.com/Saplings-Projects/1M_sub/pull/43/commits/1d7f1339c23519da8573e04da653569323651f34 once you added `_card_container` to the scene tree.

Whatever you have latest now for #43, just from pulling it and running tests everything is good 👍🏽

**Comment by Tysterman74** [comment]
At least for orphans, we should be able to test for orphans and throw an error: https://gut.readthedocs.io/en/latest/Memory-Management.html#testing-for-leaks

**Comment by Turtyo** [comment]
Yes I fixed those errors already because they were easy to spot, but the problem is that the tests are still passing on the action
For orphans we should be able to yes, and we can also throw an error if any test file is ignored i think
